airline/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include("flights.urls")),
    path('users/', include("users.urls")),
]

flights/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.index,name="index"),
    path("<int:flight_id>",views.flights,name="flights"),
]

users/urls.py
from django.urls import path

from . import views

app_name="users"

urlpatterns=[
    path("",views.index, name="index"),
    path("login/",views.lin, name="lin"),
    path("logout/<str:user>",views.lout,name="lout"),
]

flights/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
    code=models.CharField(max_length=3)
    city=models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} {self.code}"

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

class Passanger(models.Model):
    firstname = models.CharField(max_length=64)
    lastname = models.CharField(max_length=64)
    booking = models.ManyToManyField(Flight, related_name="passanger")

    def __str__(self):
        return f"{self.firstname} {self.lastname}"

users/models.py
from django.db import models

# Create your models here.

flights/views.py
from django.shortcuts import render
from flights.models import Flight, Passanger
from django import forms
# Create your views here.

def index(request):
    return render(request,"flights/index.html",{
        "flights": Flight.objects.all()
    })

def flights(request, flight_id):
    try:
        flight = Flight.objects.get(id=flight_id)

    except:
        return render(request, 'flights/notfound.html')

    if request.method=='POST':
        id = int(request.POST["passangers"])
        passanger=Passanger.objects.get(id=id)
        passanger.booking.add(flight)


    return render(request,'flights/flight.html',
                  { "flight": flight,
                    "passanger": flight.passanger.all(),
                     "non_passangers": Passanger.objects.exclude(booking=flight).all(),
                    })

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:lin'))
    return render(request,"users/index.html")

def lin(request):
    if request.method == "POST":
        username=request.POST["username"]
        password=request.POST["password"]
        user = authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse('users:index'), {"user":user})
        return render(request,"users/login.html", {"message":"wrong credentials"})
    else:
        return render(request,"users/login.html")

def lout(request,user):
    logout(request)
    return render(request,"users/logout.html",{"user": user})

flights/templates/flights/flight.html
{%extends "flights/layout.html"%}
{%block body%}
   <h1>flight number :  {{flight.id}}</h1>
<h4> from --- {{flight.origin}}</h4>
<h4>   TO --- {{flight.destination}}</h4>
<h4>  Duration ---  {{flight.duration}}</h4>
<h1>Passangers</h1>
{%for p in passanger%}
<li>{{p.firstname}} {{p.lastname}}</li>
{%empty%}
<h4>Empty</h4>
   {%endfor%}
<a href="{%url 'index'%}">flights list</a>
<h1>register for this flight</h1>
<form action="{%url 'flights' flight.id%}" method="post">
   {% csrf_token %}
        <select name="passangers">
            {%for p in non_passangers %}
            <option value="{{p.id}}">{{p}}</option>
        {%endfor%}
        </select>
        <input type="submit" value="click">
        </div>
</form>
{%endblock%}

flights/templates/flights/index.html
{% extends "flights/layout.html" %}
{%block body%}
    <h1>Flights</h1>
    {% for flight in flights %}
    <li>
        <a href="{%url 'flights' flight.id%}">
        {{flight}}
        </a>
    </li>

    {%empty%}
            <li>no flights at current moment</li>
    {%endfor%}
{%endblock%}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flights</title>
</head>
<body>
        {%block body%}
        {%endblock%}
</body>
</html>

flights/templates/flights/notfound.html
{%extends 'flights/layout.html'%}
{%load static%}
{% block body %}
    <img src="{%static 'images/naruto.png'%}" style="display: inline-block; width:7em;" class="image1">
    <img src="{%static 'images/madara.png'%}" style="display: inline-block; height:15em;" class="image2">
    <div style="font-size:5em; display:inline-block; width:4em">PAGE NOT FOUND</div>

<script>
    image1=document.querySelector(".image1")
    image2=document.querySelector(".image2")

    no=Math.floor(Math.random()*10);
    if(no>5){
    image1.style.display="none"
    image2.style.display="inline-block"
    }
    else{
    image2.style.display="none"
    image1.style.display="inline-block"
    }
</script>
{% endblock %}

users/templates/users/index.html
{%extends 'users/layout.html'%}

{%block body%}
hellno
{{user}}
<div><a href="{%url 'users:lout' user%}">logout</a>>
</div>
    {%endblock%}

users/templates/users/layout.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<link>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{%static 'login/styles.css'%}">
    <title>Users</title>
</head>
<body >
{%block body%}
{%endblock%}
</body>
</html>

users/templates/users/login.html
{%extends 'users/layout.html'%}

{%block body%}
<div>
    <div >
    <form action= "{%url 'users:lin' %}" method="post" name="user">
        {% csrf_token %}

        <input type="username" name="username">
        <input type="password" name="password">
        <input type="submit" name="submit">
</form>
    </div>
{%if message%}
<h1>{{message}}</h1>
</div>
{%endif%}
{%endblock%}

users/templates/users/logout.html
{%extends "users/layout.html"%}
{%block body%}
{{user}}

log out page
{%endblock%}